language: node_js
node_js: "node"

dist: stretch
sudo: false

addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
  - yarn test